
name: Build and Deploy
on: 
  push:
    branches:
      - main
      - pcPublishStorybook
    paths: ["stories/**", "src/components/**", ".github/workflows/**"] # Trigger the action only when files change in the folders defined here
  pull_request:
    branches:
      - main
    paths: ["stories/**", "src/components/**", ".github/workflows/**"] # Trigger the action only when files change in the folders defined here
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install and Build ğŸ”§
        working-directory: ./javascript
        run: | # Install npm packages and build the Storybook files
          npm install
          npm run build-storybook
      - name: Deploy ğŸš€
        working-directory: ./javascript
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          repository_name: ucsb-cs156-s21/demo-react-minimal-docs
          token: ${{ secrets.TOKEN }}
          branch: main # The branch the action should deploy to.
          folder: docs-build # The folder that the build-storybook script generates files.
          clean: true # Automatically remove deleted files from the deploy branch
          target_folder: docs/storybook # The folder that we serve our Storybook files from 
